# Generated by Django 5.1.6 on 2025-03-01 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='Descrpition',
            new_name='Description',
        ),
    ]
